import {
  Mail, Users, Briefcase, ListChecks, Gavel, ScrollText, FileCheck,
  BarChart3, UserCircle, LayoutGrid, Calendar, Mic, Scale, Building2,
  Info, ShoppingCart, FileText, Dog, Megaphone, Hammer, Wallet,
  BadgeCheck, Home, FileSignature, ClipboardList, ShieldCheck, Receipt,
  Gavel as Gavel2, Leaf, Wheat, Map, Heart, Tag, HardHat, Radio,
  Network, FileQuestion, AlertCircle, Landmark, BookOpen, FolderOpen,
  Eye, MessageSquare, Newspaper, FileSearch, Target, GraduationCap,
  HelpCircle, Image, Video, History, Settings, MoreHorizontal,
  LayoutDashboard, UserCog, Flag, CircleDollarSign, Folder, Euro,
  Globe, Building, Siren, TrendingUp, Send, CreditCard, Phone, Bell,
  Stethoscope, Bus, Dumbbell, Store, FileStack, BookMarked, Speech,
  FileArchive, MapPin, Clock, Palette, Award, Waves, Bird, Utensils,
  TreePine, FileSpreadsheet,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP: Record<string, LucideIcon> = {
  mail: Mail,
  users: Users,
  briefcase: Briefcase,
  listChecks: ListChecks,
  gavel: Gavel,
  scrollText: ScrollText,
  fileCheck: FileCheck,
  barChart3: BarChart3,
  userCircle: UserCircle,
  layoutGrid: LayoutGrid,
  calendar: Calendar,
  mic: Mic,
  scale: Scale,
  building2: Building2,
  info: Info,
  shoppingCart: ShoppingCart,
  fileText: FileText,
  dog: Dog,
  megaphone: Megaphone,
  hammer: Hammer,
  wallet: Wallet,
  badgeCheck: BadgeCheck,
  home: Home,
  fileSignature: FileSignature,
  clipboardList: ClipboardList,
  shieldCheck: ShieldCheck,
  receipt: Receipt,
  leaf: Leaf,
  wheat: Wheat,
  map: Map,
  heart: Heart,
  tag: Tag,
  hardHat: HardHat,
  radio: Radio,
  network: Network,
  fileQuestion: FileQuestion,
  alertCircle: AlertCircle,
  landmark: Landmark,
  bookOpen: BookOpen,
  folderOpen: FolderOpen,
  eye: Eye,
  messageSquare: MessageSquare,
  newspaper: Newspaper,
  fileSearch: FileSearch,
  target: Target,
  graduationCap: GraduationCap,
  helpCircle: HelpCircle,
  image: Image,
  video: Video,
  history: History,
  settings: Settings,
  moreHorizontal: MoreHorizontal,
  layoutDashboard: LayoutDashboard,
  userCog: UserCog,
  flag: Flag,
  circleDollarSign: CircleDollarSign,
  folder: Folder,
  euro: Euro,
  globe: Globe,
  building: Building,
  siren: Siren,
  trendingUp: TrendingUp,
  send: Send,
  creditCard: CreditCard,
  phone: Phone,
  bell: Bell,
  stethoscope: Stethoscope,
  bus: Bus,
  dumbbell: Dumbbell,
  store: Store,
  fileStack: FileStack,
  bookMarked: BookMarked,
  speech: Speech,
  fileArchive: FileArchive,
  mapPin: MapPin,
  clock: Clock,
  palette: Palette,
  award: Award,
  waves: Waves,
  bird: Bird,
  utensils: Utensils,
  treePine: TreePine,
  fileSpreadsheet: FileSpreadsheet,
};

export const ICON_OPTIONS = Object.keys(ICON_MAP).sort();

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] || FileText;
}
